"""Generate semantic, directly linkable pages for the three independent books."""
from pathlib import Path
import json, html
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'dist'
books=json.loads((OUT/'data/books.json').read_text(encoding='utf-8'))
esc=html.escape
def name(b): return b['title']+(' · '+b['season'] if b['season'] else '')
def read_url(b,n=None): return f"read-{b['id']}-{n or b['chapters'][0]['number']}.html"
def head(title,description):
    return f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)} · 霜木林</title><meta name="description" content="{esc(description)}"><meta name="theme-color" content="#e6f1f6"><link rel="icon" type="image/svg+xml" href="assets/favicon.svg"><link rel="stylesheet" href="style.css"><link rel="preload" href="assets/book-serif.woff2" as="font" type="font/woff2" crossorigin></head>'''
def header():
    return '''<a class="skip" href="#main">跳到正文</a><header class="site-header wrap"><a class="brand" href="index.html" aria-label="霜木林，返回首页"><div class="brand-logo"><img src="assets/author-logo.png" width="1280" height="1280" alt="霜木林"></div><span>个人书房</span></a><nav class="nav" aria-label="主导航"><a href="index.html#library">作品</a><a href="index.html#about">关于我</a></nav></header>'''
def footer():
    return '''<footer class="site-footer wrap"><span>© 2026 霜木林 · 故事与文字，皆有所归。</span><a href="index.html#library">回到书架 ↑</a></footer>'''
def shelf(b):
    season_label='<span class="book-season"> · '+esc(b['season'])+'</span>' if b['season'] else ''
    return f'''<article class="shelf-book"><a class="cover-stage" href="book-{b['id']}.html" aria-label="查看{name(b)}"><img src="{b['cover']}" alt="{name(b)}封面" width="740" height="1050" loading="lazy"></a><div><div class="book-meta"><span>{b['genre']}</span><span class="status">{b['status']}</span></div><h3><a href="book-{b['id']}.html">{b['title']}{season_label}</a></h3><p>{b['subtitle']}</p><div class="shelf-links"><a href="book-{b['id']}.html">翻开这本书 ↗</a><a href="{b['pdf']}" download="{name(b)}.pdf">下载 PDF ↓</a></div></div></article>'''
home=head('文字里的相遇','霜木林的个人书房。阅读《可安，向晨》第一季、第二季与《月隐之证》，也可以下载 PDF，让故事随身同行。')+'<body>'+header()+f'''<main id="main"><section class="hero wrap"><div class="hero-copy"><p class="eyebrow">正在连载 · 更新至第 {books[1]['chapters'][-1]['number']} 章</p><h1>{books[1]['title']}<span class="hero-season">{books[1]['season']}</span></h1><p>从热恋走进日常，学着理解彼此。<br>关于陪伴，也关于第一次真正的磨合。</p><div class="actions"><a class="button" href="{read_url(books[1],books[1]['chapters'][-1]['number'])}">阅读最新章 <span aria-hidden="true">↗</span></a><a class="text-link" href="{read_url(books[0])}">从第一季读起 <span aria-hidden="true">→</span></a></div></div><div class="hero-art"><img class="hero-back" src="assets/season1.jpg" alt="可安，向晨第一季封面" width="740" height="1050"><a class="hero-book" href="book-season2.html" aria-label="翻开可安，向晨第二季"><img src="assets/season2.jpg" width="740" height="1050" alt="可安，向晨第二季封面" fetchpriority="high"></a><div class="hero-caption">正在连载 · 可安，向晨 第二季</div></div></section><section class="library wrap" id="library"><h2 class="section-title">故事，都在这里。</h2><p class="section-intro">在线翻阅，或带一本 PDF 离开。</p><div class="bookshelf">{''.join(shelf(b) for b in books)}</div></section><section class="about-section" id="about"><div class="about wrap"><div class="author-art"><img src="assets/author-logo.png" width="1280" height="1280" alt="霜木林的冰霜署名" loading="lazy"></div><div><h2 class="section-title">你好，我是霜木林。</h2><p>我的创作主要围绕悬疑、日常与校园。<br>喜欢追寻平静背后的秘密，也喜欢记录普通日子里的心动与成长。</p><p>“霜木林”这个笔名，最早来自我的小名“小林”。觉得“小林”有些简单，就从“林”字里的两个“木”，想到了“双木林”，再把“双”换成“霜”。既留着小名的来处，也让这个名字多了一点自己的特色。</p><p>希望写下的故事，能陪你度过一段安静的时光。</p><p class="signature">霜木林</p></div></div></section></main>'''+footer()+'</body></html>'
(OUT/'index.html').write_text(home,encoding='utf-8')
for b in books:
    related=''
    if b['id']=='season1':related='<p class="related-note">故事继续：<a href="book-season2.html">前往第二季，未读的夜晚 →</a></p>'
    if b['id']=='season2':related='<p class="related-note">本书延续第一季，章节从第 25 章开始。<a href="book-season1.html">回到第一季 →</a></p>'
    groups=[]
    for v in sorted(set(c['volume'] for c in b['chapters'])):
        vi=v-1 if b['id']=='season1' else 0
        label=(f'第{v}卷 · ' if b['id']!='yueyin' else '')+b['volumes'][vi]
        links=''.join(f'''<li><a href="{read_url(b,c['number'])}"><span class="chapter-no">第 {c['number']} 章</span><span class="chapter-title">{esc(c['title']) or '第 '+str(c['number'])+' 章'}</span><span class="chapter-arrow" aria-hidden="true">↗</span></a></li>''' for c in b['chapters'] if c['volume']==v)
        groups.append(f'<details class="volume" open><summary>{label}</summary><ol class="chapter-list">{links}</ol></details>')
    page=head(name(b),b['description'])+'<body>'+header()+f'''<main id="main" class="wrap"><a class="breadcrumb" href="index.html#library">← 回到书架</a><section class="book-detail"><div class="detail-cover"><img src="{b['cover']}" width="740" height="1050" alt="{name(b)}封面"></div><div><div class="book-meta"><span>{b['genre']}</span><span class="status">{b['status']}</span></div><h1>{name(b)}</h1><p class="book-description">{b['description']}</p><div class="actions"><a class="button start-reading" data-book="{b['id']}" href="{read_url(b)}">开始阅读 <span aria-hidden="true">↗</span></a><a class="button secondary" href="{b['pdf']}" download="{name(b)}.pdf">下载 PDF <span aria-hidden="true">↓</span></a></div><div class="book-stats"><span>{len(b['chapters'])} 章{' · 更新至第 28 章' if b['id']=='season2' else ''}</span><span>约 {b['wordCount']/10000:.1f} 万字</span><span>PDF · {b['pdfSize']} MB</span></div>{related}</div></section><section class="contents" id="contents"><h2 class="section-title">目录</h2><p class="section-intro">选一章，继续故事。</p>{''.join(groups)}</section></main>'''+footer()+'<script src="book.js" defer></script></body></html>'
    (OUT/f"book-{b['id']}.html").write_text(page,encoding='utf-8')
reader=head('在线阅读','霜木林作品在线阅读')+'''<body class="reader-page"><a class="skip" href="#main">跳到正文</a><header class="reader-header"><a class="reader-brand" href="index.html" aria-label="返回霜木林首页"><img src="assets/author-logo.png" width="1280" height="1280" alt="霜木林"></a><a id="reader-book-link" class="reader-title-link" href="index.html#library">在线阅读</a><div class="reader-tools" aria-label="阅读设置"><span class="reader-toolbar-label">字号</span><button class="tool-button" id="smaller" type="button" aria-label="缩小字号">A−</button><button class="tool-button" id="larger" type="button" aria-label="放大字号">A＋</button><button class="tool-button" id="theme-toggle" type="button" aria-pressed="false">夜读</button><button class="tool-button" id="open-contents" type="button" aria-haspopup="dialog" disabled>目录</button></div></header><main class="reader-main" id="main"><div class="loading" role="status">正在翻开故事…</div></main><noscript><div class="noscript">在线阅读需要启用 JavaScript。你也可以<a href="index.html#library">回到书架下载 PDF</a>。</div></noscript><footer class="reader-footer">霜木林 · 愿你在故事里，停留片刻。</footer><dialog class="reader-dialog" id="contents-dialog" aria-labelledby="contents-title"><div class="dialog-header"><h2 id="contents-title">章节目录</h2><button type="button" class="tool-button" id="close-contents" aria-label="关闭目录">关闭 ×</button></div><div id="dialog-chapters"></div><a id="reader-download" class="text-link" href="index.html#library">下载本书 PDF ↓</a></dialog><div id="reader-toast" class="reader-toast" role="status" hidden></div><script src="reader.js" defer></script></body></html>'''
(OUT/'reader.html').write_text(reader,encoding='utf-8')
(OUT/'404.html').write_text(head('这一页还没有故事','页面未找到')+'<body>'+header()+'<main id="main" class="error wrap"><h1>这一页，还没有故事。</h1><p>也许地址有些小差错。回到书架，换一本继续读吧。</p><a class="button" href="index.html#library">回到书架</a></main>'+footer()+'</body></html>',encoding='utf-8')
from build_readers import build_readers
build_readers(books, reader, head, OUT)
print('Built homepage, 3 independent book pages, 41 complete reading pages, legacy reader and 404.')
